# Generated by Django 3.2.9 on 2021-11-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
